spring.application.name=edtech-backend
spring.profiles.active=dev
spring.datasource.url=jdbc:postgresql://ep-small-violet-ay1udv7g-pooler.c-5.us-east-2.aws.neon.tech/neondb?user=neondb_owner&password=npg_tprAlQ81IszT&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_tprAlQ81IszT
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.flyway.schemas=public
spring.flyway.default-schema=public
media.upload-dir=uploads
app.base-url=http://localhost:8080
spring.jpa.properties.hibernate.default_schema=public
logging.level.org.springframework.security=DEBUG
server.port=8080
# Multipart upload settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
cloudinary.cloud-name=dratlafwc
cloudinary.api-key=973655674522437
cloudinary.api-secret=TfE6eO50A06DmOuzjKJZZTXuj80