CREATE TABLE faqs
(
    id BIGSERIAL PRIMARY KEY,

    question TEXT NOT NULL,

    answer TEXT NOT NULL,

    display_order INT NOT NULL DEFAULT 0,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);