CREATE TABLE technologies
(
    id BIGSERIAL PRIMARY KEY,

    name VARCHAR(100) NOT NULL,

    icon_url TEXT,

    display_order INT NOT NULL DEFAULT 0,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);